/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as NewsSitemapDotxmlRouteImport } from './routes/news-sitemap[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IssueNumberRouteImport } from './routes/issue.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSitemapDotxmlRoute = NewsSitemapDotxmlRouteImport.update({
  id: '/news-sitemap.xml',
  path: '/news-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IssueNumberRoute = IssueNumberRouteImport.update({
  id: '/issue/$number',
  path: '/issue/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/latest': typeof LatestRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/issue/$number': typeof IssueNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/latest': typeof LatestRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/issue/$number': typeof IssueNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/latest': typeof LatestRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/issue/$number': typeof IssueNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/archive'
    | '/latest'
    | '/news-sitemap.xml'
    | '/sitemap.xml'
    | '/issue/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/archive'
    | '/latest'
    | '/news-sitemap.xml'
    | '/sitemap.xml'
    | '/issue/$number'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/archive'
    | '/latest'
    | '/news-sitemap.xml'
    | '/sitemap.xml'
    | '/issue/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchiveRoute: typeof ArchiveRoute
  LatestRoute: typeof LatestRoute
  NewsSitemapDotxmlRoute: typeof NewsSitemapDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  IssueNumberRoute: typeof IssueNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-sitemap.xml': {
      id: '/news-sitemap.xml'
      path: '/news-sitemap.xml'
      fullPath: '/news-sitemap.xml'
      preLoaderRoute: typeof NewsSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issue/$number': {
      id: '/issue/$number'
      path: '/issue/$number'
      fullPath: '/issue/$number'
      preLoaderRoute: typeof IssueNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchiveRoute: ArchiveRoute,
  LatestRoute: LatestRoute,
  NewsSitemapDotxmlRoute: NewsSitemapDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  IssueNumberRoute: IssueNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
